#!/bin/bash

set -e

echo "Updating system..."
sudo apt update -y
sudo apt upgrade -y

echo "Installing Java 17..."
sudo apt install -y openjdk-17-jdk wget unzip curl

echo "Verifying Java..."
java -version

echo "Installing PostgreSQL..."
sudo apt install -y postgresql postgresql-contrib

echo "Starting PostgreSQL..."
sudo systemctl enable postgresql
sudo systemctl start postgresql

echo "Creating SonarQube database and user..."

sudo -u postgres psql <<EOF
CREATE USER sonar WITH ENCRYPTED PASSWORD 'sonar123';
CREATE DATABASE sonarqube OWNER sonar;
GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonar;
EOF

echo "Creating SonarQube user..."
sudo useradd -r -m -d /opt/sonarqube -s /bin/bash sonar || true

cd /tmp

echo "Downloading SonarQube..."
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.6.0.109173.zip

echo "Extracting SonarQube..."
sudo unzip sonarqube-25.6.0.109173.zip -d /opt/

sudo mv /opt/sonarqube-* /opt/sonarqube

sudo chown -R sonar:sonar /opt/sonarqube

echo "Configuring SonarQube database..."

sudo tee -a /opt/sonarqube/conf/sonar.properties >/dev/null <<EOF

sonar.jdbc.username=sonar
sonar.jdbc.password=sonar123
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
EOF

echo "Increasing system limits..."

echo "vm.max_map_count=524288" | sudo tee -a /etc/sysctl.conf
echo "fs.file-max=131072" | sudo tee -a /etc/sysctl.conf

sudo sysctl -p

echo "Configuring limits..."

sudo tee -a /etc/security/limits.conf >/dev/null <<EOF
sonar   -   nofile   131072
sonar   -   nproc    8192
EOF

echo "Creating systemd service..."

sudo tee /etc/systemd/system/sonarqube.service >/dev/null <<EOF
[Unit]
Description=SonarQube Service
After=network.target postgresql.service

[Service]
Type=forking

ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

User=sonar
Group=sonar
Restart=always
LimitNOFILE=131072
LimitNPROC=8192

[Install]
WantedBy=multi-user.target
EOF

echo "Reloading systemd..."

sudo systemctl daemon-reload
sudo systemctl enable sonarqube
sudo systemctl start sonarqube

echo "Checking status..."

sleep 20

sudo systemctl status sonarqube --no-pager

echo ""
echo "==============================================="
echo "SonarQube Installation Completed"
echo "==============================================="
echo "URL: http://<SERVER-IP>:9000"
echo "Username: admin"
echo "Password: admin"
echo "==============================================="
